[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"
edition = "2018"

[workspace]
members = ["world", "display", "calx", "calx-ecs", "vitral"]

[dependencies]
calx = { path = "calx" }
calx-ecs = { path = "calx-ecs" }
display = { path = "display" }
env_logger = "0.6"
euclid = "0.20"
glium = "0.25"
log = "0.4"
rand = { version = "0.7", features = ["serde1"] }
ron = "0.5"
serde = "1.0"
structopt = "0.2"
time = "0.1"
vitral = { path = "vitral" }
world = { path = "world" }

[dev-dependencies]
image = "0.22"
serde_json = "1"
