cargo-features = ["edition"]

[package]
name = "magog"
version = "0.1.0"
authors = [ "Risto Saarelma <risto.saarelma@iki.fi>" ]
description = "Roguelike game"
keywords = ["gamedev"]
license = "GPL3"
edition = "2018"

[workspace]
members = ["world", "display", "calx", "calx-ecs", "vitral"]

[dependencies]
calx = { path = "calx" }
calx-ecs = { path = "calx-ecs" }
display = { path = "display" }
env_logger = "0.5"
euclid = "0.19"
glium = "0.22"
rand = { version = "0.5", features = ["serde1"] }
scancode = "0.1"
serde = "1.0"
time = "0.1"
vitral = { path = "vitral", features = ["glium_backend"] }
world = { path = "world" }

[dev-dependencies]
image = "0.19"
structopt = "0.2"
structopt-derive = "0.2"
