[package]
name = "world"
version = "0.1.0"
authors = [ "risto.saarelma@iki.fi" ]
edition = "2018"

[lib]
name = "world"

[dependencies]
calx = { path = "../calx" }
calx-ecs = { path = "../calx-ecs" }
euclid = "0.19"
image = "0.21"
lazy_static = "1.0"
log = "0.4"
rand = { version = "0.6", features = ["serde1"] }
rand_xorshift = "0.1"
ron = "0.4"
serde = "1.0"
serde_derive = "1.0"
vec_map = "0.8"
vitral = { path = "../vitral" }
